[package]
name = "mylauncher"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk4 = "0.8"
gdk4 = "0.8"
glib = "0.18"
gio = "0.18"
freedesktop-desktop-entry = "0.5"
nix = { version = "0.27", features = ["process"] }
shellexpand = "3.1"
dirs = "6.0"
